//Types for Add Item
export const ADDLISTITEM_REQUEST_REQUEST = 'ADDLISTITEM_REQUEST_REQUEST';
export const ADDLISTITEM_REQUEST_SUCCESS = 'ADDLISTITEM_REQUEST_SUCCESS';
export const ADDLISTITEM_REQUEST_FAILURE = 'ADDLISTITEM_REQUEST_FAILURE';

//Types for delete
export const DELETE_REQUEST_REQUEST = 'DELETE_REQUEST_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAILURE = 'DELETE_REQUEST_FAILURE';

//Types for update
export const UPDATE_REQUEST_REQUEST = 'UPDATE_REQUEST_REQUEST';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_FAILURE = 'UPDATE_REQUEST_FAILURE';
